#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"

# These files were generated by older Saw II/ReXGlue helper versions.
# None are required anymore: the current scripts apply the changes directly
# and idempotently to .deps/rexglue-sdk.
obsolete=(
  "ReXGlue-saw2-binary-patches.patch"
  "ReXGlue-timerqueue-blocking-wait.patch"
  "DisruptorPlus-blocking-wait-condvar-order.patch"
  "ReXGlue-db16cyc-noop.patch"
  "ReXGlue-db16cyc-pause.patch"
  "ReXGlue-db16cyc-pause-v2.patch"
  "ReXGlue-saw2-ue3-msaa-fix.patch"
)

removed=0
for name in "${obsolete[@]}"; do
  path="$ROOT_DIR/$name"
  if [[ -e "$path" || -L "$path" ]]; then
    rm -f -- "$path"
    printf '[saw2] removed obsolete root patch: %s\n' "$name"
    removed=1
  fi
done

if ((removed == 0)); then
  printf '[saw2] root patch cleanup: already clean\n'
fi

# Old helper revisions also left local backup files inside .deps/rexglue-sdk.
# They are never required and one could otherwise be copied into the SDK install.
SDK_DIR="$ROOT_DIR/.deps/rexglue-sdk"
if [[ -d "$SDK_DIR" ]]; then
  find "$SDK_DIR" -type f \
    \( -name '*.saw2-binary-patches.bak' \
       -o -name '*.timerqueue-blocking.bak' \
       -o -name '*.condvar-order.bak' \
       -o -name '*.db16cyc-noop.bak' \) \
    -delete 2>/dev/null || true
fi
